CREATE DATABASE IF NOT EXISTS BANKBASE
  CHARACTER SET utf8 COLLATE utf8_unicode_ci;

USE BANKBASE;

CREATE USER IF NOT EXISTS 'bank_admin'@'localhost'
  IDENTIFIED BY '67890';

CREATE TABLE IF NOT EXISTS BankT
(
  FullPrice FLOAT(8,2) NOT NULL,
  CardNumber CHAR(16) NOT NULL,
  ValidTo CHAR(4) NOT NULL,
  CvvCode CHAR(3) NOT NULL,
  ShopAccount CHAR(20) NOT NULL
)
  DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON BANKBASE.*
  TO 'bank_admin'@'localhost' IDENTIFIED BY '67890';
